### ISSUE TITLE
`dynogels` as a `peer-dependency`

### ISSUE THREAD

**Issue by ElliotChong** [andrewoh531/dynogels-promisified#2]
Should the `dynogels` dependency in `package.json` be a `peer-dependency` rather than a strict `dependency`? Doing so would allow the end-user to bring their own version of `dynogels`.

https://nodejs.org/en/blog/npm/peer-dependencies/

Ex: https://github.com/facebook/react/blob/master/packages/react-dom/package.json

**Comment by andrewoh531** [comment]
Yeap it should be a peer dependency. It's been on my mind but haven't had time to modify it.

**Comment by andrewoh531** [comment]
Fixed with commit `c9b5dc2` and released under `v1.0.3`
